version: '3.9'

services: 
  products-api:
    build: ./products-api
    environment: 
      - PORT=5001
  web-api: 
    build: ./web-api
    environment: 
      - PORT=3001
    ports: 
      - 3001:3001
    depends_on: 
      - products-api